# Generated by Django 3.2.7 on 2021-10-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_slugmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug_name',
            field=models.SlugField(default='slug'),
        ),
    ]
