# Generated by Django 3.2.7 on 2021-10-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_slug_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='slug_name',
            field=models.SlugField(default='slug<built-in function id>', unique=True),
        ),
    ]
