# Generated by Django 3.2.7 on 2021-10-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='photo',
            field=models.ImageField(upload_to="food/<method 'date' of 'datetime.datetime' objects>/"),
        ),
    ]
