# Generated by Django 3.2.7 on 2021-10-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211009_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
    ]
