# Generated by Django 3.2.7 on 2021-10-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211011_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='type',
            field=models.CharField(choices=[('Uy', 'Uyga yetkazish'), ('Stol', 'Stolga buyurtma berish')], default='Stol', max_length=10),
        ),
    ]
