# Generated by Django 3.2.7 on 2021-10-11 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='sana',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
