# Generated by Django 3.2.7 on 2021-10-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delivery_sana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='photo',
            field=models.ImageField(upload_to='food/2021-10-12/'),
        ),
    ]
